---
driver:
  name: vagrant
  network:
     - ["private_network", {ip: "192.168.33.33"}]


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[django_fun::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
